/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopproject.ui;


import com.mycompany.oopproject.SoundManager;
import com.mycompany.oopproject.gamedata;
import com.mycompany.oopproject.characters.hero;
import com.mycompany.oopproject.characters.monster;
import com.mycompany.oopproject.monsters.orc;
import com.mycompany.oopproject.monsters.dragon;
import com.mycompany.oopproject.monsters.EmptyMonster;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Phuwan
 */
public class GUIMain extends javax.swing.JFrame {
    
    private SoundManager soundManager = new SoundManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMain.class.getName());

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        soundManager.playBGM("/sounds/bgm.wav");
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLable1 = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnMage = new javax.swing.JButton();
        btnTank = new javax.swing.JButton();
        btnArcher = new javax.swing.JButton();
        btnFighter = new javax.swing.JButton();
        btnHealer = new javax.swing.JButton();
        rdMage = new javax.swing.JRadioButton();
        rdTank = new javax.swing.JRadioButton();
        rdArcher = new javax.swing.JRadioButton();
        rdFighter = new javax.swing.JRadioButton();
        rdHealer = new javax.swing.JRadioButton();
        btnStart = new javax.swing.JButton();
        btnMute = new javax.swing.JButton();
        sliderVolume = new javax.swing.JSlider();
        bgLobby = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLable1.setBackground(new java.awt.Color(242, 217, 186));
        jLable1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLable1.setText(" PLAYER NAME ");
        jLable1.setOpaque(true);
        getContentPane().add(jLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        txtPlayerName.setBackground(new java.awt.Color(242, 217, 186));
        getContentPane().add(txtPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 230, 30));

        btnMage.setBackground(new java.awt.Color(242, 217, 186));
        btnMage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mageicon.png"))); // NOI18N
        btnMage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMageMouseClicked(evt);
            }
        });
        btnMage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMageActionPerformed(evt);
            }
        });
        getContentPane().add(btnMage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 130, 150));

        btnTank.setBackground(new java.awt.Color(242, 217, 186));
        btnTank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tankicon.png"))); // NOI18N
        btnTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTankActionPerformed(evt);
            }
        });
        getContentPane().add(btnTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 130, 150));

        btnArcher.setBackground(new java.awt.Color(242, 217, 186));
        btnArcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archericon.png"))); // NOI18N
        btnArcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcherActionPerformed(evt);
            }
        });
        getContentPane().add(btnArcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 150));

        btnFighter.setBackground(new java.awt.Color(242, 217, 186));
        btnFighter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fightericon.png"))); // NOI18N
        btnFighter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFighterActionPerformed(evt);
            }
        });
        getContentPane().add(btnFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 130, 150));

        btnHealer.setBackground(new java.awt.Color(242, 217, 186));
        btnHealer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/healericon.png"))); // NOI18N
        btnHealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealerActionPerformed(evt);
            }
        });
        getContentPane().add(btnHealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 130, 150));

        rdMage.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        rdMage.setForeground(new java.awt.Color(255, 255, 255));
        rdMage.setText("MAGE");
        rdMage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdMage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdMage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rdMage.setIconTextGap(1);
        rdMage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        rdMage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMageActionPerformed(evt);
            }
        });
        getContentPane().add(rdMage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 110, 50));

        rdTank.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        rdTank.setForeground(new java.awt.Color(255, 255, 255));
        rdTank.setText("TANK");
        rdTank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rdTank.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        rdTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTankActionPerformed(evt);
            }
        });
        getContentPane().add(rdTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        rdArcher.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        rdArcher.setForeground(new java.awt.Color(255, 255, 255));
        rdArcher.setText("ARCHER");
        rdArcher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rdArcher.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        rdArcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdArcherActionPerformed(evt);
            }
        });
        getContentPane().add(rdArcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        rdFighter.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        rdFighter.setForeground(new java.awt.Color(255, 255, 255));
        rdFighter.setText("FIGHTER");
        rdFighter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rdFighter.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        rdFighter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFighterActionPerformed(evt);
            }
        });
        getContentPane().add(rdFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 130, -1));

        rdHealer.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        rdHealer.setForeground(new java.awt.Color(255, 255, 255));
        rdHealer.setText("HEALER");
        rdHealer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rdHealer.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        rdHealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHealerActionPerformed(evt);
            }
        });
        getContentPane().add(rdHealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, -1, -1));

        btnStart.setBackground(new java.awt.Color(242, 217, 186));
        btnStart.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 130, 80));

        btnMute.setBackground(new java.awt.Color(242, 217, 186));
        btnMute.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btnMute.setText("MUTE");
        btnMute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuteActionPerformed(evt);
            }
        });
        getContentPane().add(btnMute, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 70, -1));

        sliderVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVolumeStateChanged(evt);
            }
        });
        getContentPane().add(sliderVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 120, 20));

        bgLobby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgforest.png"))); // NOI18N
        getContentPane().add(bgLobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTankActionPerformed
        // TODO add your handling code here:
        StatusGui tankStatus = new StatusGui("tank");
        tankStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTankActionPerformed

    private void btnFighterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFighterActionPerformed
        // TODO add your handling code here:
        StatusGui fighterStatus = new StatusGui("fighter");
        fighterStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFighterActionPerformed

    private void rdMageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMageActionPerformed

    private void rdTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTankActionPerformed

    private void rdArcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdArcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdArcherActionPerformed

    private void rdFighterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFighterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFighterActionPerformed

    private void rdHealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHealerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdHealerActionPerformed

    private void btnMageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMageMouseClicked

    }//GEN-LAST:event_btnMageMouseClicked

    private void btnMageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMageActionPerformed
        // TODO add your handling code here:
        StatusGui mageStatus = new StatusGui("mage");
        mageStatus.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMageActionPerformed

    private void btnArcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcherActionPerformed
        // TODO add your handling code here:
        StatusGui archerStatus = new StatusGui("archer");
        archerStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArcherActionPerformed

    private void btnHealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealerActionPerformed
        // TODO add your handling code here:
        StatusGui healerStatus = new StatusGui("healer");
        healerStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHealerActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        String name = txtPlayerName.getText();
        gamedata.playerName = name.isEmpty() ? "Player": name;
        ArrayList<hero> selectedHeroes = new ArrayList<>();
        
        if (rdMage.isSelected()) {
            selectedHeroes.add(gamedata.MAGE);
        }
        if (rdTank.isSelected()) { //
            selectedHeroes.add(gamedata.TANK);
        }
        if (rdArcher.isSelected()) {
            selectedHeroes.add(gamedata.ARCHER);
        }
        if (rdFighter.isSelected()) { 
            selectedHeroes.add(gamedata.FIGHTER);
        }
        if (rdHealer.isSelected()) {
            selectedHeroes.add(gamedata.HEALER);
        }
        
        if (selectedHeroes.size() != 3) {
            JOptionPane.showMessageDialog(this, 
                "Please select 3 heroes.", 
                "Selection Error", 
                JOptionPane.WARNING_MESSAGE);
        } else {
            hero hero1 = selectedHeroes.get(0); 
            hero hero2 = selectedHeroes.get(1); 
            hero hero3 = selectedHeroes.get(2);
            
            int stage = gamedata.currentStage;
            monster m1, m2, m3;

            if (stage == gamedata.BOSS_STAGE) {
                m1 = new EmptyMonster(); 
                m2 = new EmptyMonster();
                m3 = new dragon();
            } else {
                m1 = new orc(stage);
                m2 = new orc(stage);
                m3 = new orc(stage);
            }

            
            forest map1 = new forest(hero1, hero2, hero3, m1, m2, m3);
            map1.setVisible(true);
            this.dispose();
            soundManager.stop();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnMuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuteActionPerformed
        // TODO add your handling code here:
        soundManager.toggleMute();

        if (soundManager.isMuted()) {
            btnMute.setText("UNMUTE"); 
            btnMute.setBackground(java.awt.Color.RED);
            btnMute.setForeground(java.awt.Color.WHITE);
        } else {
            btnMute.setText("MUTE");
            btnMute.setBackground(java.awt.Color.WHITE);
            btnMute.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_btnMuteActionPerformed

    private void sliderVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVolumeStateChanged
        // TODO add your handling code here:
        int sliderValue = sliderVolume.getValue();
        float volumeScale = sliderValue / 100.0f;
        soundManager.setVolume(volumeScale);

        if (sliderValue == 0) {
             btnMute.setText("UNMUTE");
        }
    }//GEN-LAST:event_sliderVolumeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIMain().setVisible(true));


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLobby;
    private javax.swing.JButton btnArcher;
    private javax.swing.JButton btnFighter;
    private javax.swing.JButton btnHealer;
    private javax.swing.JButton btnMage;
    private javax.swing.JButton btnMute;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTank;
    private javax.swing.JLabel jLable1;
    private javax.swing.JRadioButton rdArcher;
    private javax.swing.JRadioButton rdFighter;
    private javax.swing.JRadioButton rdHealer;
    private javax.swing.JRadioButton rdMage;
    private javax.swing.JRadioButton rdTank;
    private javax.swing.JSlider sliderVolume;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
