/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopproject.ui;

/**
 *
 * @author Phuwan
 */
public class IntroStory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IntroStory.class.getName());

    /**
     * Creates new form IntroStory
     */
    public IntroStory() {
        initComponents();
        
        this.setLocationRelativeTo(null);  
        this.getContentPane().setBackground(java.awt.Color.BLACK);

        String story = 
            "\u0020\u0020\u0020\u0e01\u0e32\u0e25\u0e04\u0e23\u0e31\u0e49\u0e07\u0e2b\u0e19\u0e36\u0e48\u0e07\u0e19\u0e32\u0e19\u0e21\u0e32\u0e41\u0e25\u0e49\u0e27...\n\n" +
            "\u0020\u0020\u0020\u0e13 \u0e2b\u0e21\u0e39\u0e48\u0e1a\u0e49\u0e32\u0e19\u0e17\u0e35\u0e48\u0e40\u0e04\u0e22\u0e40\u0e07\u0e35\u0e22\u0e1a\u0e2a\u0e07\u0e1a\u0e41\u0e25\u0e30\u0e2d\u0e38\u0e14\u0e21\u0e2a\u0e21\u0e1a\u0e39\u0e23\u0e13\u0e4c \u0e08\u0e39\u0e48\u0e46 \u0e17\u0e49\u0e2d\u0e07\u0e1f\u0e49\u0e32\u0e01\u0e47\u0e01\u0e25\u0e31\u0e1a\u0e21\u0e37\u0e14\u0e21\u0e34\u0e14 \n" +
            "\u0020\u0020\u0020\u0e40\u0e2a\u0e35\u0e22\u0e07\u0e04\u0e33\u0e23\u0e32\u0e21\u0e01\u0e36\u0e01\u0e01\u0e49\u0e2d\u0e07\u0e14\u0e31\u0e07\u0e21\u0e32\u0e08\u0e32\u0e01\u0e22\u0e2d\u0e14\u0e40\u0e02\u0e32\u0e28\u0e31\u0e01\u0e14\u0e34\u0e4c\u0e2a\u0e34\u0e17\u0e18\u0e34\u0e4c... \n\n" +
            "\u0020\u0020\u0020'\u0e21\u0e31\u0e07\u0e01\u0e23\u0e40\u0e1e\u0e25\u0e34\u0e07\u0e42\u0e1a\u0e23\u0e32\u0e13' \u0e44\u0e14\u0e49\u0e15\u0e37\u0e48\u0e19\u0e08\u0e32\u0e01\u0e01\u0e32\u0e23\u0e2b\u0e25\u0e31\u0e1a\u0e43\u0e2b\u0e25! \n" +
            "\u0020\u0020\u0020\u0e40\u0e1b\u0e25\u0e27\u0e40\u0e1e\u0e25\u0e34\u0e07\u0e02\u0e2d\u0e07\u0e21\u0e31\u0e19\u0e41\u0e1c\u0e14\u0e40\u0e1c\u0e32\u0e2b\u0e21\u0e39\u0e48\u0e1a\u0e49\u0e32\u0e19\u0e08\u0e19\u0e27\u0e2d\u0e14\u0e27\u0e32\u0e22 \u0e1c\u0e39\u0e49\u0e04\u0e19\u0e15\u0e48\u0e32\u0e07\u0e2b\u0e27\u0e32\u0e14\u0e01\u0e25\u0e31\u0e27\u0e41\u0e25\u0e30\u0e2a\u0e34\u0e49\u0e19\u0e2b\u0e27\u0e31\u0e07\n\n" +
            "\u0020\u0020\u0020\u0e21\u0e35\u0e40\u0e1e\u0e35\u0e22\u0e07 '\u0e01\u0e25\u0e38\u0e48\u0e21\u0e1c\u0e39\u0e49\u0e01\u0e25\u0e49\u0e32' \u0e40\u0e17\u0e48\u0e32\u0e19\u0e31\u0e49\u0e19\u0e17\u0e35\u0e48\u0e08\u0e30\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e2b\u0e22\u0e38\u0e14\u0e22\u0e31\u0e49\u0e07\u0e2b\u0e32\u0e22\u0e19\u0e30\u0e04\u0e23\u0e31\u0e49\u0e07\u0e19\u0e35\u0e49\u0e44\u0e14\u0e49...\n" +
            "\u0020\u0020\u0020\u0e08\u0e07\u0e23\u0e27\u0e1a\u0e23\u0e27\u0e21\u0e17\u0e35\u0e21 \u0e41\u0e02\u0e47\u0e07\u0e41\u0e01\u0e23\u0e48\u0e07\u0e02\u0e36\u0e49\u0e19 \u0e41\u0e25\u0e30\u0e44\u0e1b\u0e1b\u0e23\u0e32\u0e1a\u0e21\u0e31\u0e07\u0e01\u0e23\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e01\u0e2d\u0e1a\u0e01\u0e39\u0e49\u0e42\u0e25\u0e01\u0e43\u0e1a\u0e19\u0e35\u0e49!\n\n" +
            "\u0020\u0020\u0020\u0e01\u0e32\u0e23\u0e1c\u0e08\u0e0d\u0e20\u0e31\u0e22\u0e02\u0e2d\u0e07\u0e04\u0e38\u0e13... \u0e40\u0e23\u0e34\u0e48\u0e21\u0e15\u0e49\u0e19\u0e02\u0e36\u0e49\u0e19 \u0e13 \u0e1a\u0e31\u0e14\u0e19\u0e35\u0e49!";

        
        jTextArea1.setText(story);
        jTextArea1.setFont(new java.awt.Font("Angsana New", 0, 24)); 
        jTextArea1.setForeground(java.awt.Color.WHITE);
        jTextArea1.setBackground(java.awt.Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dragon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THE LEGEND OF DRAGON");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("asd");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("ENTRY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new GUIMain().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IntroStory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
