/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.oopproject.ui;

import com.mycompany.oopproject.gamedata;
import com.mycompany.oopproject.characters.Item;
import com.mycompany.oopproject.characters.hero;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Phuwan
 */
public class ItemRewardScreen extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ItemRewardScreen.class.getName());
    
    private ArrayList<hero> winningHeroes;
    private List<Item> items;
    
    /**
     * Creates new form ItemRewardScreen
     */
    public ItemRewardScreen(java.awt.Frame parent, boolean modal, ArrayList<hero> heroes) {
        super(parent, modal);
        initComponents();
        
        this.winningHeroes = heroes;
        this.setLocationRelativeTo(parent);
        this.setDefaultCloseOperation(javax.swing.JDialog.DO_NOTHING_ON_CLOSE);

        this.items = gamedata.getRandomItems(3);

        btnItem1.setText(items.get(0).getName());
        btnItem1.setToolTipText(items.get(0).getDescription());

        btnItem2.setText(items.get(1).getName());
        btnItem2.setToolTipText(items.get(1).getDescription());

        btnItem3.setText(items.get(2).getName());
        btnItem3.setToolTipText(items.get(2).getDescription());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnItem1 = new javax.swing.JButton();
        btnItem2 = new javax.swing.JButton();
        btnItem3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(253, 150));

        btnItem1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnItem1.setText("jButton1");
        btnItem1.setMaximumSize(new java.awt.Dimension(165, 24));
        btnItem1.setMinimumSize(new java.awt.Dimension(165, 24));
        btnItem1.setPreferredSize(new java.awt.Dimension(165, 24));
        btnItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItem1ActionPerformed(evt);
            }
        });

        btnItem2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnItem2.setText("jButton2");
        btnItem2.setMaximumSize(new java.awt.Dimension(104, 24));
        btnItem2.setMinimumSize(new java.awt.Dimension(104, 24));
        btnItem2.setPreferredSize(new java.awt.Dimension(104, 24));
        btnItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItem2ActionPerformed(evt);
            }
        });

        btnItem3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnItem3.setText("jButton3");
        btnItem3.setMaximumSize(new java.awt.Dimension(120, 24));
        btnItem3.setMinimumSize(new java.awt.Dimension(120, 24));
        btnItem3.setPreferredSize(new java.awt.Dimension(120, 24));
        btnItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItem3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyStatsAndClose(Item chosenItem) {
        for (hero h : winningHeroes) {
            h.applyItemStats(chosenItem);
        }
        this.dispose();
    }
    
    private void btnItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItem1ActionPerformed
        // TODO add your handling code here:
        applyStatsAndClose(items.get(0));
    }//GEN-LAST:event_btnItem1ActionPerformed

    private void btnItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItem2ActionPerformed
        // TODO add your handling code here:
        applyStatsAndClose(items.get(1));
    }//GEN-LAST:event_btnItem2ActionPerformed

    private void btnItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItem3ActionPerformed
        // TODO add your handling code here:
        applyStatsAndClose(items.get(2));
    }//GEN-LAST:event_btnItem3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItem1;
    private javax.swing.JButton btnItem2;
    private javax.swing.JButton btnItem3;
    // End of variables declaration//GEN-END:variables
}
