/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.oopproject.ui;

import com.mycompany.oopproject.characters.hero;
import java.util.ArrayList;

/**
 *
 * @author Phuwan
 */
public class RewardScreen extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RewardScreen.class.getName());

    /**
     * Creates new form RewardScreen
     */
    
    private ArrayList<hero> winningHeroes;
    
    public RewardScreen(java.awt.Frame parent, boolean modal, ArrayList<hero> heroes) {
        super(parent, modal);
        initComponents();
        
        this.winningHeroes = heroes;
        this.setLocationRelativeTo(parent);
        this.setDefaultCloseOperation(javax.swing.JDialog.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtk = new javax.swing.JButton();
        btnHp = new javax.swing.JButton();
        btnMana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAtk.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnAtk.setText("All Skill Damage +1");
        btnAtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtkActionPerformed(evt);
            }
        });

        btnHp.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnHp.setText("Max HP +2");
        btnHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpActionPerformed(evt);
            }
        });

        btnMana.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnMana.setText("Max Mana +2");
        btnMana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAtk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMana, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAtk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMana)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtkActionPerformed
        // TODO add your handling code here:
        for (hero h : winningHeroes) {
            h.upgradeAllSkills(1);
        }
        this.dispose();
    }//GEN-LAST:event_btnAtkActionPerformed

    private void btnHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpActionPerformed
        // TODO add your handling code here:
        for (hero h : winningHeroes) {
            h.upgradeMaxHp(2);
        }
        this.dispose();
    }//GEN-LAST:event_btnHpActionPerformed

    private void btnManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManaActionPerformed
        // TODO add your handling code here:
        for (hero h : winningHeroes) {
            h.upgradeMaxMana(2);
        }
        this.dispose();
    }//GEN-LAST:event_btnManaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtk;
    private javax.swing.JButton btnHp;
    private javax.swing.JButton btnMana;
    // End of variables declaration//GEN-END:variables
}
