/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopproject.ui;

import com.mycompany.oopproject.heroes.archer;
import com.mycompany.oopproject.heroes.fighter;
import com.mycompany.oopproject.heroes.healer;
import com.mycompany.oopproject.characters.hero;
import com.mycompany.oopproject.heroes.mage;
import com.mycompany.oopproject.heroes.tank;
import com.mycompany.oopproject.ui.GUIMain;
import com.mycompany.oopproject.gamedata;

/**
 *
 * @author Phuwan
 */
public class StatusGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatusGui.class.getName());

    /**
     * Creates new form MageStatusGui
     */
    
    private hero character;
    
    public StatusGui(String x) {
        initComponents();
        
        switch (x.toLowerCase()) {
            case "mage" -> character = gamedata.MAGE;
            case "tank" -> character = gamedata.TANK;
            case "fighter" -> character = gamedata.FIGHTER;
            case "healer" -> character = gamedata.HEALER;
            case "archer" -> character = gamedata.ARCHER;
            default -> throw new IllegalArgumentException("Unknown hero type: " + x);
        }
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(character.getImagePath())));
        jLabel2.setText("MAXHP : " + character.getMaxhp());
        jLabel4.setText("MAXMANA : " + character.getmana());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackToLobby = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bgLobby = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackToLobby.setBackground(new java.awt.Color(242, 217, 186));
        btnBackToLobby.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnBackToLobby.setText("BACK");
        btnBackToLobby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToLobbyMouseClicked(evt);
            }
        });
        btnBackToLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLobbyActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToLobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 50));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 390, 450));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setText("MAXHP : 7 ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 150, 20));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setText("MAXMANA : 8");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 140, 20));

        jLabel3.setBackground(new java.awt.Color(242, 217, 186));
        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 460, 320));

        bgLobby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgforest.png"))); // NOI18N
        getContentPane().add(bgLobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLobbyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBackToLobbyActionPerformed

    private void btnBackToLobbyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToLobbyMouseClicked
        // TODO add your handling code here:่
        GUIMain mainGui = new GUIMain();
        mainGui.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackToLobbyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StatusGui("mage").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLobby;
    private javax.swing.JButton btnBackToLobby;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
